import { HardwareModule, ModuleType, MountType } from './types';

export const INITIAL_MODULES: HardwareModule[] = [
  // --- LCP-1 (Garage) ---
  {
    id: 'lcp1-enc',
    name: 'Saginaw SCE-24H2408LP',
    manufacturer: 'Saginaw',
    description: '24x24x8 NEMA 4/12 Hinged',
    location: 'LCP-1',
    type: ModuleType.ENCLOSURE,
    mountType: MountType.SURFACE,
    size: 0,
    cost: 394.30, // MeCampbell Pricing
    powerWatts: 0,
    quantity: 1,
    url: 'https://www.mecampbell.com/saginaw-control-sce-24h2408lp-single-hinged-door-enclosure-with-door-cllamps-carbon-steel-gray-nema-4-12-13-iec-ip66-24x24x8-sub-panel-ordered-separately.html',
    backupUrl: 'https://www.google.com/search?q=buy+Saginaw+SCE-24H2408LP',
    dimensions: { width: 24, height: 24, depth: 8, unit: 'in' },
    notes: 'FIRE CODE: Surface mount. NEMA 4/12 Sealed (Better than NEMA 1).',
    position: { x: 72, y: 60 } // Garage area
  },
  {
    id: 'lcp1-sub',
    name: 'Saginaw SCE-24P24',
    manufacturer: 'Saginaw',
    description: 'Sub-Panel (Backplate)',
    location: 'LCP-1',
    type: ModuleType.ACCESSORY,
    mountType: MountType.SURFACE,
    size: 0,
    cost: 42.50, // JMAC Pricing
    powerWatts: 0,
    quantity: 1,
    url: 'https://www.radwell.com/Search?q=SCE-24P24',
    backupUrl: 'https://www.google.com/search?q=buy+Saginaw+SCE-24P24',
    notes: 'Required to mount DIN rails.'
  },
  {
    id: 'lcp1-din',
    name: 'DIN Rail 35mm Slotted',
    manufacturer: 'Generic',
    description: '10-Pack (Aluminum) 1 Meter',
    location: 'LCP-1',
    type: ModuleType.ACCESSORY,
    mountType: MountType.SURFACE,
    size: 0,
    cost: 35.00,
    powerWatts: 0,
    quantity: 1,
    url: 'https://www.amazon.com/s?k=din+rail+slotted+aluminum+10+pack',
    backupUrl: 'https://www.radwell.com/Search?q=DIN+Rail+35mm',
    notes: 'Cut to size for Backplate (Horizontal rows).'
  },
  //...
  {
    id: 'lcp1-acc-psu',
    name: 'Altronix eFlow6N',
    manufacturer: 'Altronix',
    description: 'Access Power Controller',
    location: 'LCP-1',
    type: ModuleType.POWER,
    mountType: MountType.WALL_MOUNT,
    size: 0,
    cost: 320.00,
    powerWatts: 10,
    quantity: 1,
    url: 'https://www.jmac.com/search.php?search_query=eFlow6N',
    notes: 'Powers HES Strikes. High inrush current handling. Battery Backup.'
  },
  //...
  {
    id: 'cable-knx',
    name: 'KNX Bus Cable',
    manufacturer: 'Belden',
    description: '2500 ft (2-pair Shielded)',
    location: 'Infra',
    type: ModuleType.ACCESSORY,
    mountType: MountType.NA,
    size: 0,
    cost: 850.00,
    powerWatts: 0,
    quantity: 1,
    url: 'https://www.jmac.com/search.php?search_query=Belden+YE00906',
    notes: 'Green sheath.'
  },

  {
    id: 'lcp1-gw1',
    name: 'DALI Control Gateway',
    manufacturer: 'MDT',
    description: 'SCN-DALI64.03 (Uni 3)',
    location: 'LCP-1',
    type: ModuleType.LIGHTING,
    mountType: MountType.DIN_RAIL,
    size: 4,
    cost: 385.00,
    powerWatts: 2,
    heatDissipation: 2,
    quantity: 1,
    url: 'https://www.mdt.de/en/products/product-detail/actuators/dali-gateways/dali-control-ip-gateway.html',
    notes: 'Universe 3',
    universe: 3
  },
  {
    id: 'lcp1-gw2',
    name: 'DALI Control Gateway',
    manufacturer: 'MDT',
    description: 'SCN-DALI64.03 (Uni 4)',
    location: 'LCP-1',
    type: ModuleType.LIGHTING,
    mountType: MountType.DIN_RAIL,
    size: 4,
    cost: 385.00,
    powerWatts: 2,
    heatDissipation: 2,
    quantity: 1,
    url: 'https://www.mdt.de/en/products/product-detail/actuators/dali-gateways/dali-control-ip-gateway.html',
    notes: 'Universe 4',
    universe: 4
  },
  {
    id: 'lcp1-fan',
    name: 'DALI 0-10V Interface',
    manufacturer: 'Lunatone',
    description: '86458668 (Powder Fan)',
    location: 'LCP-1',
    type: ModuleType.HVAC,
    mountType: MountType.DIN_RAIL,
    size: 2,
    cost: 82.50,
    powerWatts: 1,
    quantity: 1,
    url: 'https://www.lunatone.com/en/product/dali-0-10v-pwm-interface/',
    notes: 'Control for Panasonic FV-1115VQ1',
    universe: 3
  },
  {
    id: 'lcp1-drv',
    name: 'DALI DT8 Dimmer 16A',
    manufacturer: 'Lunatone',
    description: '89453841-HS (High Current)',
    location: 'LCP-1',
    type: ModuleType.LIGHTING,
    mountType: MountType.DIN_RAIL,
    size: 4,
    cost: 118.00,
    powerWatts: 5,
    heatDissipation: 10, // Significant heat
    quantity: 4,
    url: 'https://www.lunatone.com/en/product/dali-dt8-dimmer-cv-16a/',
    notes: 'Garage/Kitchen Tape. High heat output.',
    universe: 3
  },
  {
    id: 'lcp1-rel',
    name: 'Switch Actuator 12-fold',
    manufacturer: 'MDT',
    description: 'AKS-1216.03',
    location: 'LCP-1',
    type: ModuleType.CONTROLLER,
    mountType: MountType.DIN_RAIL,
    size: 8,
    cost: 315.00,
    powerWatts: 1,
    quantity: 1,
    url: 'https://www.mdt.de/en/products/product-detail/actuators/switch-actuators/switch-actuator-aks-standard.html',
    notes: 'Switched Loads (Xmas/Attic)'
  },
  {
    id: 'lcp1-inp',
    name: 'Binary Input 16-fold',
    manufacturer: 'MDT',
    description: 'BE-16000.02 (Security)',
    location: 'LCP-1',
    type: ModuleType.SENSOR,
    mountType: MountType.DIN_RAIL,
    size: 8,
    cost: 285.00,
    powerWatts: 0.5,
    quantity: 1,
    url: 'https://www.mdt.de/en/products/product-detail/sensors/binary-inputs/binary-input-potential-free.html',
    notes: 'Security Sensors'
  },
  {
    id: 'lcp1-psu1',
    name: 'SDR-480-24 PSU',
    manufacturer: 'Mean Well',
    description: '480W 24V (Garage LEDs)',
    location: 'LCP-1',
    type: ModuleType.POWER,
    mountType: MountType.DIN_RAIL,
    size: 5, // 85.5mm is approx 5TE
    cost: 158.00,
    powerWatts: 480,
    heatDissipation: 34, // ~7% loss at full load
    quantity: 1,
    url: 'https://www.amazon.com/s?k=MEAN+WELL+SDR-480-24',
    backupUrl: 'https://www.google.com/search?q=buy+Mean+Well+SDR-480-24',
    notes: 'Dedicated for Garage LEDs. Requires air gap.'
  },
  {
    id: 'lcp1-psu2',
    name: 'HDR-150-24 PSU',
    manufacturer: 'Mean Well',
    description: '150W 24V (Kitchen LEDs)',
    location: 'LCP-1',
    type: ModuleType.POWER,
    mountType: MountType.DIN_RAIL,
    size: 6, // 105mm
    cost: 52.00,
    powerWatts: 150,
    heatDissipation: 15,
    quantity: 1,
    url: 'https://www.meanwell.com/productWebApp/product/view/HDR-150',
    notes: 'Kitchen LEDs'
  },
  {
    id: 'lcp1-sys',
    name: 'IP Router / Bus Pwr',
    manufacturer: 'MDT',
    description: 'SCN-IPR300.03',
    location: 'LCP-1',
    type: ModuleType.NETWORK,
    mountType: MountType.DIN_RAIL,
    size: 2,
    cost: 445.00,
    powerWatts: 3,
    quantity: 1,
    url: 'https://www.mdt.de/en/products/product-detail/system-components/system-devices/ip-router.html'
  },

  // --- LCP-2 (Office #2) ---
  {
    id: 'lcp2-enc',
    name: 'Leviton 47605-21E',
    manufacturer: 'Leviton',
    description: '21" Structured Media Enclosure',
    location: 'LCP-2',
    type: ModuleType.ENCLOSURE,
    mountType: MountType.FLUSH,
    size: 0,
    cost: 92.45, // JMAC Pricing
    powerWatts: 0,
    quantity: 1,
    url: 'https://www.jmac.com/Leviton_47605_21E_p/leviton-47605-21e.htm',
    dimensions: { width: 14.5, height: 21, depth: 3.75, unit: 'in' },
    notes: 'FRAMING ALERT: Stud bay is 18". Block down to 14.5".',
    position: { x: 35, y: 55 } // Near Office 2
  },
  {
    id: 'lcp2-door',
    name: 'Leviton 47605-21S',
    manufacturer: 'Leviton',
    description: 'Vented Door (White)',
    location: 'LCP-2',
    type: ModuleType.ACCESSORY,
    mountType: MountType.FLUSH,
    size: 0,
    cost: 58.75, // JMAC Pricing
    powerWatts: 0,
    quantity: 1,
    url: 'https://www.jmac.com/Leviton_47605_21S_p/leviton-47605-21s.htm'
  },
  {
    id: 'lcp2-brkt',
    name: 'Leviton DIN Bracket',
    manufacturer: 'Leviton',
    description: '47605-DIN (Vertical)',
    location: 'LCP-2',
    type: ModuleType.ACCESSORY,
    mountType: MountType.FLUSH,
    size: 0,
    cost: 18.00,
    powerWatts: 0,
    quantity: 2,
    url: 'https://www.jmac.com/Leviton_47605_DIN_p/leviton-47605-din.htm',
    notes: 'Vertical mount brackets'
  },
  {
    id: 'lcp2-gw1',
    name: 'DALI Control Gateway',
    manufacturer: 'MDT',
    description: 'SCN-DALI64.03 (Uni 1)',
    location: 'LCP-2',
    type: ModuleType.LIGHTING,
    mountType: MountType.DIN_RAIL,
    size: 4,
    cost: 385.00,
    powerWatts: 2,
    quantity: 1,
    url: 'https://www.mdt.de/en/products/product-detail/actuators/dali-gateways/dali-control-ip-gateway.html',
    notes: 'Universe 1',
    universe: 1
  },
  {
    id: 'lcp2-gw2',
    name: 'DALI Control Gateway',
    manufacturer: 'MDT',
    description: 'SCN-DALI64.03 (Uni 2)',
    location: 'LCP-2',
    type: ModuleType.LIGHTING,
    mountType: MountType.DIN_RAIL,
    size: 4,
    cost: 385.00,
    powerWatts: 2,
    quantity: 1,
    url: 'https://www.mdt.de/en/products/product-detail/actuators/dali-gateways/dali-control-ip-gateway.html',
    notes: 'Universe 2',
    universe: 2
  },
  {
    id: 'lcp2-fan',
    name: 'DALI 0-10V Interface',
    manufacturer: 'Lunatone',
    description: '86458668 (Fans)',
    location: 'LCP-2',
    type: ModuleType.HVAC,
    mountType: MountType.DIN_RAIL,
    size: 2,
    cost: 82.50,
    powerWatts: 1,
    quantity: 5,
    url: 'https://www.lunatone.com/en/product/dali-0-10v-pwm-interface/',
    notes: 'Bath Fans + Laundry',
    universe: 1
  },
  {
    id: 'lcp2-drv',
    name: 'DALI DT8 Dimmer 16A',
    manufacturer: 'Lunatone',
    description: '89453841-HS',
    location: 'LCP-2',
    type: ModuleType.LIGHTING,
    mountType: MountType.DIN_RAIL,
    size: 4,
    cost: 118.00,
    powerWatts: 5,
    heatDissipation: 10,
    quantity: 2,
    url: 'https://www.lunatone.com/en/product/dali-dt8-dimmer-cv-16a/',
    notes: 'Master Coves',
    universe: 1
  },
  {
    id: 'lcp2-inp',
    name: 'Binary Input 16-fold',
    manufacturer: 'MDT',
    description: 'BE-16000.02',
    location: 'LCP-2',
    type: ModuleType.SENSOR,
    mountType: MountType.DIN_RAIL,
    size: 8,
    cost: 285.00,
    powerWatts: 0.5,
    quantity: 1,
    url: 'https://www.mdt.de/en/products/product-detail/sensors/binary-inputs/binary-input-potential-free.html',
    notes: 'Closet/Room Sensors'
  },
  {
    id: 'lcp2-psu',
    name: 'HDR-150-24 PSU',
    manufacturer: 'Mean Well',
    description: '150W 24V (Master LEDs)',
    location: 'LCP-2',
    type: ModuleType.POWER,
    mountType: MountType.DIN_RAIL,
    size: 6,
    cost: 52.00,
    powerWatts: 150,
    heatDissipation: 15,
    quantity: 1,
    url: 'https://www.meanwell.com/productWebApp/product/view/HDR-150',
    notes: 'Master LEDs'
  },
  {
    id: 'lcp2-sys',
    name: 'IP Router / Bus Pwr',
    manufacturer: 'MDT',
    description: 'SCN-IPR300.03',
    location: 'LCP-2',
    type: ModuleType.NETWORK,
    mountType: MountType.DIN_RAIL,
    size: 2,
    cost: 445.00,
    powerWatts: 3,
    quantity: 1,
    url: 'https://www.mdt.de/en/products/product-detail/system-components/system-devices/ip-router.html'
  },

  // --- MDF (Tech Room) ---
  {
    id: 'mdf-nuc',
    name: 'ASUS NUC 13 Pro',
    manufacturer: 'ASUS',
    description: 'Home Assistant Server',
    location: 'MDF',
    type: ModuleType.CONTROLLER,
    mountType: MountType.RACK_UNIT,
    size: 1,
    cost: 620.00,
    powerWatts: 45,
    quantity: 1,
    url: 'https://www.asus.com/us/displays-desktops/nucs/nuc-kits/asus-nuc-13-pro-kit/',
    notes: 'Runs Home Assistant OS + Asterisk (SIP Server) for Intercom.',
    position: { x: 62, y: 38 } // Tech Room
  },
  {
    id: 'mdf-sw',
    name: 'UniFi Pro Max 24 PoE',
    manufacturer: 'Ubiquiti',
    description: 'Core Switch',
    location: 'MDF',
    type: ModuleType.NETWORK,
    mountType: MountType.RACK_UNIT,
    size: 1,
    cost: 799.00,
    powerWatts: 50,
    quantity: 1,
    url: 'https://store.ui.com/us/en/pro/category/all-switching/products/usw-pro-max-24-poe',
    notes: 'Core Switch',
    position: { x: 62, y: 39 }
  },
  {
    id: 'mdf-velux',
    name: 'KLF 200 Bridge',
    manufacturer: 'Velux',
    description: 'Skylight Interface',
    location: 'MDF',
    type: ModuleType.CONTROLLER,
    mountType: MountType.WALL_MOUNT,
    size: 0,
    cost: 325.00,
    powerWatts: 5,
    quantity: 1,
    url: 'https://www.amazon.com/Velux-Home-Automation-Integration-Kit/dp/B079979G5H',
    notes: 'Skylights & Shades',
    position: { x: 63, y: 37 }
  },
  {
    id: 'mdf-sen1',
    name: 'SDP810 Pressure Sensor',
    manufacturer: 'Sensirion',
    description: 'HVAC Pressure',
    location: 'MDF',
    type: ModuleType.SENSOR,
    mountType: MountType.NA,
    size: 0,
    cost: 48.00,
    powerWatts: 0.1,
    quantity: 1,
    url: 'https://sensirion.com/products/catalog/SDP810-500Pa',
    notes: 'Pneumatic tube to roof'
  },
  {
    id: 'mdf-sen2',
    name: 'RG-11 Rain Sensor',
    manufacturer: 'Hydreon',
    description: 'Optical Rain Sensor',
    location: 'MDF',
    type: ModuleType.SENSOR,
    mountType: MountType.WALL_MOUNT,
    size: 0,
    cost: 99.00,
    powerWatts: 1,
    quantity: 1,
    url: 'https://rainsensors.com/'
  },

  // --- Field Devices ---
  {
    id: 'field-kp',
    name: 'Glass Push Button II Smart',
    manufacturer: 'MDT',
    description: 'BE-GT2TS.02 Black',
    location: 'Field',
    type: ModuleType.CONTROLLER,
    mountType: MountType.WALL_MOUNT,
    size: 0,
    cost: 215.00,
    powerWatts: 0.5,
    quantity: 16,
    url: 'https://www.mdt.de/en/products/product-detail/sensors/push-buttons/glass-push-button-ii-smart.html',
    notes: '16 Locations. Requires 1-Gang Mud Ring.',
    position: { x: 45, y: 70 } // Mock Position for one
  },
  {
    id: 'field-sen-tp',
    name: 'TruePresence Multisensor',
    manufacturer: 'Steinel',
    description: 'VOC/CO2/Humidity/Temp',
    location: 'Field',
    type: ModuleType.SENSOR,
    mountType: MountType.CEILING_MOUNT,
    size: 0,
    cost: 245.00,
    powerWatts: 1,
    quantity: 6,
    url: 'https://www.steinel.de/en/group/sensors/smart-space-sensors/true-presence/true-presence-multisensor-aerosol-knx.html',
    notes: 'Baths (4) + Powder + Laundry',
    position: { x: 25, y: 35 } // Master Bath
  },
  {
    id: 'field-sen-tpk',
    name: 'TruePresence KNX',
    manufacturer: 'Steinel',
    description: 'Light Level/Breathing',
    location: 'Field',
    type: ModuleType.SENSOR,
    mountType: MountType.CEILING_MOUNT,
    size: 0,
    cost: 195.00,
    powerWatts: 1,
    quantity: 3,
    url: 'https://www.steinel.de/en/group/sensors/smart-space-sensors/true-presence/true-presence-knx.html',
    notes: 'Kitchen, Living, Master',
    position: { x: 55, y: 45 } // Kitchen area
  },
  {
    id: 'field-ak-x915',
    name: 'X915 Door Phone',
    manufacturer: 'Akuvox',
    description: 'Flagship Touchscreen',
    location: 'Field',
    type: ModuleType.SECURITY,
    mountType: MountType.WALL_MOUNT,
    size: 0,
    cost: 2800.00,
    powerWatts: 12,
    quantity: 1,
    url: 'https://akuvoxdealer.com/?s=x915',
    notes: 'Main Entry. Install back-box before stone.',
    position: { x: 40, y: 80 } // Entry
  },
  {
    id: 'field-ak-e16',
    name: 'E16 Door Phone',
    manufacturer: 'Akuvox',
    description: 'Face Recognition',
    location: 'Field',
    type: ModuleType.SECURITY,
    mountType: MountType.WALL_MOUNT,
    size: 0,
    cost: 620.00,
    powerWatts: 10,
    quantity: 3,
    url: 'https://akuvoxdealer.com/products/akuvox-e16c-facial-recognition-door-phone',
    notes: 'Side/Garage doors. PoE.'
  },
  {
    id: 'field-str',
    name: '1006 Electric Strike',
    manufacturer: 'HES',
    description: 'Heavy Duty Fail Secure',
    location: 'Field',
    type: ModuleType.SECURITY,
    mountType: MountType.WALL_MOUNT,
    size: 0,
    cost: 385.00, // JMAC Pricing
    powerWatts: 8,
    quantity: 4,
    url: 'https://www.jmac.com/HES_1006_Series_Electric_Strike_Body_p/hes-1006.htm',
    notes: 'Fail Secure. Requires diode protection.'
  },
  {
    id: 'lcp1-acc-psu',
    name: 'Altronix eFlow6N',
    manufacturer: 'Altronix',
    description: 'Access Power Controller',
    location: 'LCP-1',
    type: ModuleType.POWER,
    mountType: MountType.WALL_MOUNT,
    size: 0,
    cost: 320.00,
    powerWatts: 10,
    quantity: 1,
    url: 'https://www.amazon.com/s?k=Altronix+eFlow6N',
    backupUrl: 'https://www.jmac.com/search.php?search_query=eFlow6N',
    notes: 'Powers HES Strikes. High inrush current handling. Battery Backup.'
  },
  {
    id: 'field-puck',
    name: 'DALI-2 PD Phase Dimmer',
    manufacturer: 'Lunatone',
    description: 'Retrofit Puck',
    location: 'Field',
    type: ModuleType.LIGHTING,
    mountType: MountType.CEILING_MOUNT,
    size: 0,
    cost: 98.00,
    powerWatts: 0.5,
    quantity: 8,
    url: 'https://www.eibabo.com/en/search?sSearch=lunatone+dali-2+pd',
    notes: 'Install in attic J-Box near fixture.',
    universe: 1,
    position: { x: 50, y: 40 } // Dining
  },
  {
    id: 'cable-knx',
    name: 'KNX Bus Cable',
    manufacturer: 'Belden',
    description: '2500 ft (2-pair Shielded)',
    location: 'Infra',
    type: ModuleType.ACCESSORY,
    mountType: MountType.NA,
    size: 0,
    cost: 850.00,
    powerWatts: 0,
    quantity: 1,
    url: 'https://www.jmac.com/search.php?search_query=Belden+YE00906',
    notes: 'Green sheath.'
  },
  {
    id: 'cable-cat6',
    name: 'Cat6 / Cat6a Riser',
    manufacturer: 'TrueCable',
    description: '3000 ft Bulk',
    location: 'Infra',
    type: ModuleType.ACCESSORY,
    mountType: MountType.NA,
    size: 0,
    cost: 550.00, // Blended cost
    powerWatts: 0,
    quantity: 1,
    url: 'https://www.truecable.com/pages/search-results-page?q=cat6+riser',
    notes: '3000ft total est. Use Cat6a for high-bandwidth/PoE++, Cat6 for standard.'
  },
];

export const MOCK_CONNECTIONS = [
  { id: 'c1', fromModuleId: 'lcp1-psu1', toModuleId: 'lcp1-gw1', type: 'Mains 24V' },
  { id: 'c2', fromModuleId: 'lcp1-sys', toModuleId: 'lcp1-gw1', type: 'KNX Bus' },
  { id: 'c3', fromModuleId: 'lcp1-gw1', toModuleId: 'field-puck', type: 'DALI' },
  { id: 'c4', fromModuleId: 'mdf-sw', toModuleId: 'lcp1-sys', type: 'Ethernet' },
  { id: 'c5', fromModuleId: 'mdf-sw', toModuleId: 'lcp2-sys', type: 'Ethernet' },
  { id: 'c6', fromModuleId: 'mdf-sw', toModuleId: 'field-ak-x915', type: 'PoE' },
];