
import React from 'react';
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer';
import { CircuitLoad } from '../../src/services/AmpereEngine';

const styles = StyleSheet.create({
    page: { padding: 40, backgroundColor: '#ffffff', fontFamily: 'Helvetica' },
    header: { marginBottom: 20, borderBottom: 1, paddingBottom: 10 },
    title: { fontSize: 24, fontWeight: 'bold', color: '#1e293b' },
    subtitle: { fontSize: 10, color: '#64748b', marginTop: 4, textTransform: 'uppercase', letterSpacing: 1 },
    section: { marginTop: 20 },
    table: { display: 'flex', width: 'auto', marginTop: 10 },
    tableRow: { flexDirection: 'row', borderBottomWidth: 0.5, borderBottomColor: '#e2e8f0', minHeight: 25, alignItems: 'center' },
    tableHeader: { backgroundColor: '#f8fafc', fontWeight: 'bold' },
    tableColId: { width: '20%', fontSize: 9, padding: 5 },
    tableColLoad: { width: '15%', fontSize: 9, padding: 5 },
    tableColStatus: { width: '15%', fontSize: 9, padding: 5 },
    tableColDevices: { width: '50%', fontSize: 8, padding: 5, color: '#475569' },
    danger: { color: '#ef4444', fontWeight: 'bold' },
    success: { color: '#10b981' },
    footer: { position: 'absolute', bottom: 30, left: 40, right: 40, borderTop: 1, paddingTop: 10, fontSize: 8, color: '#94a3b8', textAlign: 'center' }
});

interface Props {
    projectName: string;
    circuits: CircuitLoad[];
}

export const HVCircuitSchedule: React.FC<Props> = ({ projectName, circuits }) => (
    <Document title="HV Circuit Schedule">
        <Page size="A4" style={styles.page}>
            <View style={styles.header}>
                <Text style={styles.title}>HV Circuit Schedule</Text>
                <Text style={styles.subtitle}>{projectName} | Technical Report</Text>
            </View>

            <View style={styles.section}>
                <View style={styles.table}>
                    <View style={[styles.tableRow, styles.tableHeader]}>
                        <Text style={styles.tableColId}>Circuit ID</Text>
                        <Text style={styles.tableColLoad}>Total Amps</Text>
                        <Text style={styles.tableColStatus}>Status</Text>
                        <Text style={styles.tableColDevices}>Connected Devices</Text>
                    </View>

                    {circuits.map((c) => (
                        <View key={c.id} style={styles.tableRow}>
                            <Text style={styles.tableColId}>{c.id}</Text>
                            <Text style={[styles.tableColLoad, c.isOverloaded ? styles.danger : {}]}>
                                {c.totalAmps.toFixed(2)}A
                            </Text>
                            <Text style={[styles.tableColStatus, c.isOverloaded ? styles.danger : styles.success]}>
                                {c.isOverloaded ? 'OVERLOAD' : 'OK'}
                            </Text>
                            <Text style={styles.tableColDevices}>
                                {c.devices.length} fixtures: {c.devices.slice(0, 5).join(', ')}{c.devices.length > 5 ? '...' : ''}
                            </Text>
                        </View>
                    ))}
                </View>
            </View>

            <Text style={styles.footer}>
                Generated by IntegratorPro Component-First Engine | Schema 2.0 | Page 1 of 1
            </Text>
        </Page>
    </Document>
);
